#############################################################################
# Makefile for building: web_app
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  web_app.pro
# Template: app
# Command: /home/fzk/anaconda3/bin/qmake -o Makefile web_app.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../anaconda3/include/qt -I../../../anaconda3/include/qt/QtWidgets -I../../../anaconda3/include/qt/QtGui -I../../../anaconda3/include/qt/QtNetwork -I../../../anaconda3/include/qt/QtCore -I. -I. -I../../../anaconda3/mkspecs/linux-g++
QMAKE         = /home/fzk/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/fzk/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/fzk/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = web_app1.0.0
DISTDIR = /home/fzk/401/src/web_app/.tmp/web_app1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/fzk/anaconda3/lib
LIBS          = $(SUBLIBS) -lrt -L/home/fzk/anaconda3/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		net_speed.cpp \
		common.cpp \
		tcpserver.cpp moc_mainwindow.cpp \
		moc_tcpserver.cpp
OBJECTS       = main.o \
		mainwindow.o \
		net_speed.o \
		common.o \
		tcpserver.o \
		moc_mainwindow.o \
		moc_tcpserver.o
DIST          = ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/warn_on.prf \
		../../../anaconda3/mkspecs/features/qt.prf \
		../../../anaconda3/mkspecs/features/resources.prf \
		../../../anaconda3/mkspecs/features/moc.prf \
		../../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../../anaconda3/mkspecs/features/uic.prf \
		../../../anaconda3/mkspecs/features/unix/thread.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		web_app.pro mainwindow.h \
		common.h \
		packet.h \
		net_speed.h \
		tcpserver.h main.cpp \
		mainwindow.cpp \
		net_speed.cpp \
		common.cpp \
		tcpserver.cpp
QMAKE_TARGET  = web_app
DESTDIR       = 
TARGET        = web_app


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: web_app.pro ../../../anaconda3/mkspecs/linux-g++/qmake.conf ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/warn_on.prf \
		../../../anaconda3/mkspecs/features/qt.prf \
		../../../anaconda3/mkspecs/features/resources.prf \
		../../../anaconda3/mkspecs/features/moc.prf \
		../../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../../anaconda3/mkspecs/features/uic.prf \
		../../../anaconda3/mkspecs/features/unix/thread.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		web_app.pro \
		../../../anaconda3/lib/libQt5Widgets.prl \
		../../../anaconda3/lib/libQt5Gui.prl \
		../../../anaconda3/lib/libQt5Network.prl \
		../../../anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile web_app.pro
../../../anaconda3/mkspecs/features/spec_pre.prf:
../../../anaconda3/mkspecs/common/unix.conf:
../../../anaconda3/mkspecs/common/linux.conf:
../../../anaconda3/mkspecs/common/sanitize.conf:
../../../anaconda3/mkspecs/common/gcc-base.conf:
../../../anaconda3/mkspecs/common/gcc-base-unix.conf:
../../../anaconda3/mkspecs/common/g++-base.conf:
../../../anaconda3/mkspecs/common/g++-unix.conf:
../../../anaconda3/mkspecs/qconfig.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda3/mkspecs/features/qt_functions.prf:
../../../anaconda3/mkspecs/features/qt_config.prf:
../../../anaconda3/mkspecs/linux-g++/qmake.conf:
../../../anaconda3/mkspecs/features/spec_post.prf:
../../../anaconda3/mkspecs/features/exclusive_builds.prf:
../../../anaconda3/mkspecs/features/toolchain.prf:
../../../anaconda3/mkspecs/features/default_pre.prf:
../../../anaconda3/mkspecs/features/resolve_config.prf:
../../../anaconda3/mkspecs/features/default_post.prf:
../../../anaconda3/mkspecs/features/warn_on.prf:
../../../anaconda3/mkspecs/features/qt.prf:
../../../anaconda3/mkspecs/features/resources.prf:
../../../anaconda3/mkspecs/features/moc.prf:
../../../anaconda3/mkspecs/features/unix/opengl.prf:
../../../anaconda3/mkspecs/features/uic.prf:
../../../anaconda3/mkspecs/features/unix/thread.prf:
../../../anaconda3/mkspecs/features/qmake_use.prf:
../../../anaconda3/mkspecs/features/file_copies.prf:
../../../anaconda3/mkspecs/features/testcase_targets.prf:
../../../anaconda3/mkspecs/features/exceptions.prf:
../../../anaconda3/mkspecs/features/yacc.prf:
../../../anaconda3/mkspecs/features/lex.prf:
web_app.pro:
../../../anaconda3/lib/libQt5Widgets.prl:
../../../anaconda3/lib/libQt5Gui.prl:
../../../anaconda3/lib/libQt5Network.prl:
../../../anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile web_app.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h common.h packet.h net_speed.h tcpserver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp net_speed.cpp common.cpp tcpserver.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_tcpserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_tcpserver.cpp
moc_mainwindow.cpp: ../../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtGui/qtgui-config.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtCore/qmargins.h \
		../../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda3/include/qt/QtCore/qrect.h \
		../../../anaconda3/include/qt/QtCore/qsize.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtGui/qpalette.h \
		../../../anaconda3/include/qt/QtGui/qcolor.h \
		../../../anaconda3/include/qt/QtGui/qrgb.h \
		../../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../../anaconda3/include/qt/QtGui/qbrush.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../../anaconda3/include/qt/QtGui/qregion.h \
		../../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qline.h \
		../../../anaconda3/include/qt/QtGui/qtransform.h \
		../../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../../anaconda3/include/qt/QtGui/qimage.h \
		../../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtGui/qfont.h \
		../../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../../anaconda3/include/qt/QtGui/qcursor.h \
		../../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../../anaconda3/include/qt/QtGui/qevent.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qurl.h \
		../../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../../anaconda3/include/qt/QtCore/qfile.h \
		../../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../../anaconda3/include/qt/QtGui/qicon.h \
		tcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/QTcpServer \
		../../../anaconda3/include/qt/QtNetwork/qtcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkglobal.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetwork-config.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qhostaddress.h \
		../../../anaconda3/include/qt/QtNetwork/QtNetwork \
		../../../anaconda3/include/qt/QtNetwork/QtNetworkDepends \
		../../../anaconda3/include/qt/QtCore/QtCore \
		../../../anaconda3/include/qt/QtCore/QtCoreDepends \
		../../../anaconda3/include/qt/QtCore/qabstractanimation.h \
		../../../anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		../../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		../../../anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractstate.h \
		../../../anaconda3/include/qt/QtCore/qabstracttransition.h \
		../../../anaconda3/include/qt/QtCore/qanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qarraydataops.h \
		../../../anaconda3/include/qt/QtCore/qarraydatapointer.h \
		../../../anaconda3/include/qt/QtCore/qbasictimer.h \
		../../../anaconda3/include/qt/QtCore/qbitarray.h \
		../../../anaconda3/include/qt/QtCore/qbuffer.h \
		../../../anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		../../../anaconda3/include/qt/QtCore/qcache.h \
		../../../anaconda3/include/qt/QtCore/qcollator.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineoption.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineparser.h \
		../../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../../anaconda3/include/qt/QtCore/qcryptographichash.h \
		../../../anaconda3/include/qt/QtCore/qdatetime.h \
		../../../anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		../../../anaconda3/include/qt/QtCore/qelapsedtimer.h \
		../../../anaconda3/include/qt/QtCore/qdir.h \
		../../../anaconda3/include/qt/QtCore/qfileinfo.h \
		../../../anaconda3/include/qt/QtCore/qdiriterator.h \
		../../../anaconda3/include/qt/QtCore/qeasingcurve.h \
		../../../anaconda3/include/qt/QtCore/qendian.h \
		../../../anaconda3/include/qt/QtCore/qeventtransition.h \
		../../../anaconda3/include/qt/QtCore/qexception.h \
		../../../anaconda3/include/qt/QtCore/qfactoryinterface.h \
		../../../anaconda3/include/qt/QtCore/qfileselector.h \
		../../../anaconda3/include/qt/QtCore/QObject \
		../../../anaconda3/include/qt/QtCore/QStringList \
		../../../anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		../../../anaconda3/include/qt/QtCore/qfinalstate.h \
		../../../anaconda3/include/qt/QtCore/qfuture.h \
		../../../anaconda3/include/qt/QtCore/qfutureinterface.h \
		../../../anaconda3/include/qt/QtCore/qrunnable.h \
		../../../anaconda3/include/qt/QtCore/qresultstore.h \
		../../../anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		../../../anaconda3/include/qt/QtCore/qfuturewatcher.h \
		../../../anaconda3/include/qt/QtCore/qhistorystate.h \
		../../../anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qisenum.h \
		../../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../../anaconda3/include/qt/QtCore/qjsonarray.h \
		../../../anaconda3/include/qt/QtCore/qjsonvalue.h \
		../../../anaconda3/include/qt/QtCore/qjsondocument.h \
		../../../anaconda3/include/qt/QtCore/qjsonobject.h \
		../../../anaconda3/include/qt/QtCore/qlibrary.h \
		../../../anaconda3/include/qt/QtCore/qlibraryinfo.h \
		../../../anaconda3/include/qt/QtCore/qversionnumber.h \
		../../../anaconda3/include/qt/QtCore/qlinkedlist.h \
		../../../anaconda3/include/qt/QtCore/qlockfile.h \
		../../../anaconda3/include/qt/QtCore/qloggingcategory.h \
		../../../anaconda3/include/qt/QtCore/qmath.h \
		../../../anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		../../../anaconda3/include/qt/QtCore/qmetaobject.h \
		../../../anaconda3/include/qt/QtCore/qmimedata.h \
		../../../anaconda3/include/qt/QtCore/qmimedatabase.h \
		../../../anaconda3/include/qt/QtCore/qmimetype.h \
		../../../anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		../../../anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		../../../anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qpauseanimation.h \
		../../../anaconda3/include/qt/QtCore/qplugin.h \
		../../../anaconda3/include/qt/QtCore/qpointer.h \
		../../../anaconda3/include/qt/QtCore/qpluginloader.h \
		../../../anaconda3/include/qt/QtCore/qprocess.h \
		../../../anaconda3/include/qt/QtCore/qpropertyanimation.h \
		../../../anaconda3/include/qt/QtCore/qvariantanimation.h \
		../../../anaconda3/include/qt/QtCore/qqueue.h \
		../../../anaconda3/include/qt/QtCore/qreadwritelock.h \
		../../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../../anaconda3/include/qt/QtCore/qresource.h \
		../../../anaconda3/include/qt/QtCore/qsavefile.h \
		../../../anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		../../../anaconda3/include/qt/QtCore/qsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qsettings.h \
		../../../anaconda3/include/qt/QtCore/qsharedmemory.h \
		../../../anaconda3/include/qt/QtCore/qsignalmapper.h \
		../../../anaconda3/include/qt/QtCore/qsignaltransition.h \
		../../../anaconda3/include/qt/QtCore/qsocketnotifier.h \
		../../../anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qstack.h \
		../../../anaconda3/include/qt/QtCore/qstandardpaths.h \
		../../../anaconda3/include/qt/QtCore/qstate.h \
		../../../anaconda3/include/qt/QtCore/qstatemachine.h \
		../../../anaconda3/include/qt/QtCore/qstorageinfo.h \
		../../../anaconda3/include/qt/QtCore/qstringlistmodel.h \
		../../../anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qtemporarydir.h \
		../../../anaconda3/include/qt/QtCore/QScopedPointer \
		../../../anaconda3/include/qt/QtCore/qtemporaryfile.h \
		../../../anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		../../../anaconda3/include/qt/QtCore/qtextcodec.h \
		../../../anaconda3/include/qt/QtCore/qthread.h \
		../../../anaconda3/include/qt/QtCore/qthreadpool.h \
		../../../anaconda3/include/qt/QtCore/qthreadstorage.h \
		../../../anaconda3/include/qt/QtCore/qtimeline.h \
		../../../anaconda3/include/qt/QtCore/qtimer.h \
		../../../anaconda3/include/qt/QtCore/qtimezone.h \
		../../../anaconda3/include/qt/QtCore/qtranslator.h \
		../../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../../anaconda3/include/qt/QtCore/quuid.h \
		../../../anaconda3/include/qt/QtCore/qwaitcondition.h \
		../../../anaconda3/include/qt/QtCore/qwineventnotifier.h \
		../../../anaconda3/include/qt/QtCore/qxmlstream.h \
		../../../anaconda3/include/qt/QtCore/qtcoreversion.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractnetworkcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkrequest.h \
		../../../anaconda3/include/qt/QtCore/QSharedDataPointer \
		../../../anaconda3/include/qt/QtCore/QString \
		../../../anaconda3/include/qt/QtCore/QUrl \
		../../../anaconda3/include/qt/QtCore/QVariant \
		../../../anaconda3/include/qt/QtNetwork/qauthenticator.h \
		../../../anaconda3/include/qt/QtNetwork/qdnslookup.h \
		../../../anaconda3/include/qt/QtNetwork/qhostinfo.h \
		../../../anaconda3/include/qt/QtNetwork/qhstspolicy.h \
		../../../anaconda3/include/qt/QtNetwork/qhttpmultipart.h \
		../../../anaconda3/include/qt/QtCore/QByteArray \
		../../../anaconda3/include/qt/QtCore/QIODevice \
		../../../anaconda3/include/qt/QtNetwork/QNetworkRequest \
		../../../anaconda3/include/qt/QtNetwork/qlocalserver.h \
		../../../anaconda3/include/qt/QtNetwork/qlocalsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkaccessmanager.h \
		../../../anaconda3/include/qt/QtCore/QVector \
		../../../anaconda3/include/qt/QtNetwork/QSslConfiguration \
		../../../anaconda3/include/qt/QtNetwork/qsslconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qsslsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtcpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslerror.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificate.h \
		../../../anaconda3/include/qt/QtNetwork/qssl.h \
		../../../anaconda3/include/qt/QtCore/QFlags \
		../../../anaconda3/include/qt/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../anaconda3/include/qt/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../anaconda3/include/qt/QtCore/QMetaType \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookie.h \
		../../../anaconda3/include/qt/QtCore/QList \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookiejar.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdatagram.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdiskcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkinterface.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkproxy.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkreply.h \
		../../../anaconda3/include/qt/QtNetwork/QNetworkAccessManager \
		../../../anaconda3/include/qt/QtNetwork/qnetworksession.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificateextension.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcipher.h \
		../../../anaconda3/include/qt/QtNetwork/qssldiffiehellmanparameters.h \
		../../../anaconda3/include/qt/QtNetwork/qsslellipticcurve.h \
		../../../anaconda3/include/qt/QtCore/QHash \
		../../../anaconda3/include/qt/QtNetwork/qsslkey.h \
		../../../anaconda3/include/qt/QtNetwork/qudpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkversion.h \
		../../../anaconda3/include/qt/QtCore/QDataStream \
		../../../anaconda3/include/qt/QtCore/QTextStream \
		mainwindow.h \
		moc_predefs.h \
		../../../anaconda3/bin/moc
	/home/fzk/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/fzk/anaconda3/mkspecs/linux-g++ -I/home/fzk/401/src/web_app -I/home/fzk/anaconda3/include/qt -I/home/fzk/anaconda3/include/qt/QtWidgets -I/home/fzk/anaconda3/include/qt/QtGui -I/home/fzk/anaconda3/include/qt/QtNetwork -I/home/fzk/anaconda3/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_tcpserver.cpp: ../../../anaconda3/include/qt/QtNetwork/QTcpServer \
		../../../anaconda3/include/qt/QtNetwork/qtcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetwork-config.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractsocket.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtNetwork/qhostaddress.h \
		tcpserver.h \
		moc_predefs.h \
		../../../anaconda3/bin/moc
	/home/fzk/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/fzk/anaconda3/mkspecs/linux-g++ -I/home/fzk/401/src/web_app -I/home/fzk/anaconda3/include/qt -I/home/fzk/anaconda3/include/qt/QtWidgets -I/home/fzk/anaconda3/include/qt/QtGui -I/home/fzk/anaconda3/include/qt/QtNetwork -I/home/fzk/anaconda3/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tcpserver.h -o moc_tcpserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../anaconda3/bin/uic
	/home/fzk/anaconda3/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtGui/qtgui-config.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtCore/qmargins.h \
		../../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda3/include/qt/QtCore/qrect.h \
		../../../anaconda3/include/qt/QtCore/qsize.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtGui/qpalette.h \
		../../../anaconda3/include/qt/QtGui/qcolor.h \
		../../../anaconda3/include/qt/QtGui/qrgb.h \
		../../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../../anaconda3/include/qt/QtGui/qbrush.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../../anaconda3/include/qt/QtGui/qregion.h \
		../../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qline.h \
		../../../anaconda3/include/qt/QtGui/qtransform.h \
		../../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../../anaconda3/include/qt/QtGui/qimage.h \
		../../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtGui/qfont.h \
		../../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../../anaconda3/include/qt/QtGui/qcursor.h \
		../../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../../anaconda3/include/qt/QtGui/qevent.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qurl.h \
		../../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../../anaconda3/include/qt/QtCore/qfile.h \
		../../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../../anaconda3/include/qt/QtGui/qicon.h \
		tcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/QTcpServer \
		../../../anaconda3/include/qt/QtNetwork/qtcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkglobal.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetwork-config.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qhostaddress.h \
		../../../anaconda3/include/qt/QtNetwork/QtNetwork \
		../../../anaconda3/include/qt/QtNetwork/QtNetworkDepends \
		../../../anaconda3/include/qt/QtCore/QtCore \
		../../../anaconda3/include/qt/QtCore/QtCoreDepends \
		../../../anaconda3/include/qt/QtCore/qabstractanimation.h \
		../../../anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		../../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		../../../anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractstate.h \
		../../../anaconda3/include/qt/QtCore/qabstracttransition.h \
		../../../anaconda3/include/qt/QtCore/qanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qarraydataops.h \
		../../../anaconda3/include/qt/QtCore/qarraydatapointer.h \
		../../../anaconda3/include/qt/QtCore/qbasictimer.h \
		../../../anaconda3/include/qt/QtCore/qbitarray.h \
		../../../anaconda3/include/qt/QtCore/qbuffer.h \
		../../../anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		../../../anaconda3/include/qt/QtCore/qcache.h \
		../../../anaconda3/include/qt/QtCore/qcollator.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineoption.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineparser.h \
		../../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../../anaconda3/include/qt/QtCore/qcryptographichash.h \
		../../../anaconda3/include/qt/QtCore/qdatetime.h \
		../../../anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		../../../anaconda3/include/qt/QtCore/qelapsedtimer.h \
		../../../anaconda3/include/qt/QtCore/qdir.h \
		../../../anaconda3/include/qt/QtCore/qfileinfo.h \
		../../../anaconda3/include/qt/QtCore/qdiriterator.h \
		../../../anaconda3/include/qt/QtCore/qeasingcurve.h \
		../../../anaconda3/include/qt/QtCore/qendian.h \
		../../../anaconda3/include/qt/QtCore/qeventtransition.h \
		../../../anaconda3/include/qt/QtCore/qexception.h \
		../../../anaconda3/include/qt/QtCore/qfactoryinterface.h \
		../../../anaconda3/include/qt/QtCore/qfileselector.h \
		../../../anaconda3/include/qt/QtCore/QObject \
		../../../anaconda3/include/qt/QtCore/QStringList \
		../../../anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		../../../anaconda3/include/qt/QtCore/qfinalstate.h \
		../../../anaconda3/include/qt/QtCore/qfuture.h \
		../../../anaconda3/include/qt/QtCore/qfutureinterface.h \
		../../../anaconda3/include/qt/QtCore/qrunnable.h \
		../../../anaconda3/include/qt/QtCore/qresultstore.h \
		../../../anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		../../../anaconda3/include/qt/QtCore/qfuturewatcher.h \
		../../../anaconda3/include/qt/QtCore/qhistorystate.h \
		../../../anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qisenum.h \
		../../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../../anaconda3/include/qt/QtCore/qjsonarray.h \
		../../../anaconda3/include/qt/QtCore/qjsonvalue.h \
		../../../anaconda3/include/qt/QtCore/qjsondocument.h \
		../../../anaconda3/include/qt/QtCore/qjsonobject.h \
		../../../anaconda3/include/qt/QtCore/qlibrary.h \
		../../../anaconda3/include/qt/QtCore/qlibraryinfo.h \
		../../../anaconda3/include/qt/QtCore/qversionnumber.h \
		../../../anaconda3/include/qt/QtCore/qlinkedlist.h \
		../../../anaconda3/include/qt/QtCore/qlockfile.h \
		../../../anaconda3/include/qt/QtCore/qloggingcategory.h \
		../../../anaconda3/include/qt/QtCore/qmath.h \
		../../../anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		../../../anaconda3/include/qt/QtCore/qmetaobject.h \
		../../../anaconda3/include/qt/QtCore/qmimedata.h \
		../../../anaconda3/include/qt/QtCore/qmimedatabase.h \
		../../../anaconda3/include/qt/QtCore/qmimetype.h \
		../../../anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		../../../anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		../../../anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qpauseanimation.h \
		../../../anaconda3/include/qt/QtCore/qplugin.h \
		../../../anaconda3/include/qt/QtCore/qpointer.h \
		../../../anaconda3/include/qt/QtCore/qpluginloader.h \
		../../../anaconda3/include/qt/QtCore/qprocess.h \
		../../../anaconda3/include/qt/QtCore/qpropertyanimation.h \
		../../../anaconda3/include/qt/QtCore/qvariantanimation.h \
		../../../anaconda3/include/qt/QtCore/qqueue.h \
		../../../anaconda3/include/qt/QtCore/qreadwritelock.h \
		../../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../../anaconda3/include/qt/QtCore/qresource.h \
		../../../anaconda3/include/qt/QtCore/qsavefile.h \
		../../../anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		../../../anaconda3/include/qt/QtCore/qsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qsettings.h \
		../../../anaconda3/include/qt/QtCore/qsharedmemory.h \
		../../../anaconda3/include/qt/QtCore/qsignalmapper.h \
		../../../anaconda3/include/qt/QtCore/qsignaltransition.h \
		../../../anaconda3/include/qt/QtCore/qsocketnotifier.h \
		../../../anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qstack.h \
		../../../anaconda3/include/qt/QtCore/qstandardpaths.h \
		../../../anaconda3/include/qt/QtCore/qstate.h \
		../../../anaconda3/include/qt/QtCore/qstatemachine.h \
		../../../anaconda3/include/qt/QtCore/qstorageinfo.h \
		../../../anaconda3/include/qt/QtCore/qstringlistmodel.h \
		../../../anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qtemporarydir.h \
		../../../anaconda3/include/qt/QtCore/QScopedPointer \
		../../../anaconda3/include/qt/QtCore/qtemporaryfile.h \
		../../../anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		../../../anaconda3/include/qt/QtCore/qtextcodec.h \
		../../../anaconda3/include/qt/QtCore/qthread.h \
		../../../anaconda3/include/qt/QtCore/qthreadpool.h \
		../../../anaconda3/include/qt/QtCore/qthreadstorage.h \
		../../../anaconda3/include/qt/QtCore/qtimeline.h \
		../../../anaconda3/include/qt/QtCore/qtimer.h \
		../../../anaconda3/include/qt/QtCore/qtimezone.h \
		../../../anaconda3/include/qt/QtCore/qtranslator.h \
		../../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../../anaconda3/include/qt/QtCore/quuid.h \
		../../../anaconda3/include/qt/QtCore/qwaitcondition.h \
		../../../anaconda3/include/qt/QtCore/qwineventnotifier.h \
		../../../anaconda3/include/qt/QtCore/qxmlstream.h \
		../../../anaconda3/include/qt/QtCore/qtcoreversion.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractnetworkcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkrequest.h \
		../../../anaconda3/include/qt/QtCore/QSharedDataPointer \
		../../../anaconda3/include/qt/QtCore/QString \
		../../../anaconda3/include/qt/QtCore/QUrl \
		../../../anaconda3/include/qt/QtCore/QVariant \
		../../../anaconda3/include/qt/QtNetwork/qauthenticator.h \
		../../../anaconda3/include/qt/QtNetwork/qdnslookup.h \
		../../../anaconda3/include/qt/QtNetwork/qhostinfo.h \
		../../../anaconda3/include/qt/QtNetwork/qhstspolicy.h \
		../../../anaconda3/include/qt/QtNetwork/qhttpmultipart.h \
		../../../anaconda3/include/qt/QtCore/QByteArray \
		../../../anaconda3/include/qt/QtCore/QIODevice \
		../../../anaconda3/include/qt/QtNetwork/QNetworkRequest \
		../../../anaconda3/include/qt/QtNetwork/qlocalserver.h \
		../../../anaconda3/include/qt/QtNetwork/qlocalsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkaccessmanager.h \
		../../../anaconda3/include/qt/QtCore/QVector \
		../../../anaconda3/include/qt/QtNetwork/QSslConfiguration \
		../../../anaconda3/include/qt/QtNetwork/qsslconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qsslsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtcpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslerror.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificate.h \
		../../../anaconda3/include/qt/QtNetwork/qssl.h \
		../../../anaconda3/include/qt/QtCore/QFlags \
		../../../anaconda3/include/qt/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../anaconda3/include/qt/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../anaconda3/include/qt/QtCore/QMetaType \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookie.h \
		../../../anaconda3/include/qt/QtCore/QList \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookiejar.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdatagram.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdiskcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkinterface.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkproxy.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkreply.h \
		../../../anaconda3/include/qt/QtNetwork/QNetworkAccessManager \
		../../../anaconda3/include/qt/QtNetwork/qnetworksession.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificateextension.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcipher.h \
		../../../anaconda3/include/qt/QtNetwork/qssldiffiehellmanparameters.h \
		../../../anaconda3/include/qt/QtNetwork/qsslellipticcurve.h \
		../../../anaconda3/include/qt/QtCore/QHash \
		../../../anaconda3/include/qt/QtNetwork/qsslkey.h \
		../../../anaconda3/include/qt/QtNetwork/qudpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkversion.h \
		../../../anaconda3/include/qt/QtCore/QDataStream \
		../../../anaconda3/include/qt/QtCore/QTextStream \
		../../../anaconda3/include/qt/QtWidgets/QApplication \
		../../../anaconda3/include/qt/QtWidgets/qapplication.h \
		../../../anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../../anaconda3/include/qt/QtGui/qguiapplication.h \
		../../../anaconda3/include/qt/QtGui/qinputmethod.h \
		net_speed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../../../anaconda3/include/qt/QtGui/qtguiglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtGui/qtgui-config.h \
		../../../anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtCore/qmargins.h \
		../../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../../anaconda3/include/qt/QtCore/qrect.h \
		../../../anaconda3/include/qt/QtCore/qsize.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtGui/qpalette.h \
		../../../anaconda3/include/qt/QtGui/qcolor.h \
		../../../anaconda3/include/qt/QtGui/qrgb.h \
		../../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../../anaconda3/include/qt/QtGui/qbrush.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../../anaconda3/include/qt/QtGui/qregion.h \
		../../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qline.h \
		../../../anaconda3/include/qt/QtGui/qtransform.h \
		../../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../../anaconda3/include/qt/QtGui/qimage.h \
		../../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtGui/qfont.h \
		../../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../../anaconda3/include/qt/QtGui/qcursor.h \
		../../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../../anaconda3/include/qt/QtGui/qevent.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qurl.h \
		../../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../../anaconda3/include/qt/QtCore/qfile.h \
		../../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../../anaconda3/include/qt/QtGui/qicon.h \
		tcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/QTcpServer \
		../../../anaconda3/include/qt/QtNetwork/qtcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkglobal.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetwork-config.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qhostaddress.h \
		../../../anaconda3/include/qt/QtNetwork/QtNetwork \
		../../../anaconda3/include/qt/QtNetwork/QtNetworkDepends \
		../../../anaconda3/include/qt/QtCore/QtCore \
		../../../anaconda3/include/qt/QtCore/QtCoreDepends \
		../../../anaconda3/include/qt/QtCore/qabstractanimation.h \
		../../../anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		../../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		../../../anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qabstractstate.h \
		../../../anaconda3/include/qt/QtCore/qabstracttransition.h \
		../../../anaconda3/include/qt/QtCore/qanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qarraydataops.h \
		../../../anaconda3/include/qt/QtCore/qarraydatapointer.h \
		../../../anaconda3/include/qt/QtCore/qbasictimer.h \
		../../../anaconda3/include/qt/QtCore/qbitarray.h \
		../../../anaconda3/include/qt/QtCore/qbuffer.h \
		../../../anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		../../../anaconda3/include/qt/QtCore/qcache.h \
		../../../anaconda3/include/qt/QtCore/qcollator.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineoption.h \
		../../../anaconda3/include/qt/QtCore/qcommandlineparser.h \
		../../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../../anaconda3/include/qt/QtCore/qcryptographichash.h \
		../../../anaconda3/include/qt/QtCore/qdatetime.h \
		../../../anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		../../../anaconda3/include/qt/QtCore/qelapsedtimer.h \
		../../../anaconda3/include/qt/QtCore/qdir.h \
		../../../anaconda3/include/qt/QtCore/qfileinfo.h \
		../../../anaconda3/include/qt/QtCore/qdiriterator.h \
		../../../anaconda3/include/qt/QtCore/qeasingcurve.h \
		../../../anaconda3/include/qt/QtCore/qendian.h \
		../../../anaconda3/include/qt/QtCore/qeventtransition.h \
		../../../anaconda3/include/qt/QtCore/qexception.h \
		../../../anaconda3/include/qt/QtCore/qfactoryinterface.h \
		../../../anaconda3/include/qt/QtCore/qfileselector.h \
		../../../anaconda3/include/qt/QtCore/QObject \
		../../../anaconda3/include/qt/QtCore/QStringList \
		../../../anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		../../../anaconda3/include/qt/QtCore/qfinalstate.h \
		../../../anaconda3/include/qt/QtCore/qfuture.h \
		../../../anaconda3/include/qt/QtCore/qfutureinterface.h \
		../../../anaconda3/include/qt/QtCore/qrunnable.h \
		../../../anaconda3/include/qt/QtCore/qresultstore.h \
		../../../anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		../../../anaconda3/include/qt/QtCore/qfuturewatcher.h \
		../../../anaconda3/include/qt/QtCore/qhistorystate.h \
		../../../anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qisenum.h \
		../../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../../anaconda3/include/qt/QtCore/qjsonarray.h \
		../../../anaconda3/include/qt/QtCore/qjsonvalue.h \
		../../../anaconda3/include/qt/QtCore/qjsondocument.h \
		../../../anaconda3/include/qt/QtCore/qjsonobject.h \
		../../../anaconda3/include/qt/QtCore/qlibrary.h \
		../../../anaconda3/include/qt/QtCore/qlibraryinfo.h \
		../../../anaconda3/include/qt/QtCore/qversionnumber.h \
		../../../anaconda3/include/qt/QtCore/qlinkedlist.h \
		../../../anaconda3/include/qt/QtCore/qlockfile.h \
		../../../anaconda3/include/qt/QtCore/qloggingcategory.h \
		../../../anaconda3/include/qt/QtCore/qmath.h \
		../../../anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		../../../anaconda3/include/qt/QtCore/qmetaobject.h \
		../../../anaconda3/include/qt/QtCore/qmimedata.h \
		../../../anaconda3/include/qt/QtCore/qmimedatabase.h \
		../../../anaconda3/include/qt/QtCore/qmimetype.h \
		../../../anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		../../../anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		../../../anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qpauseanimation.h \
		../../../anaconda3/include/qt/QtCore/qplugin.h \
		../../../anaconda3/include/qt/QtCore/qpointer.h \
		../../../anaconda3/include/qt/QtCore/qpluginloader.h \
		../../../anaconda3/include/qt/QtCore/qprocess.h \
		../../../anaconda3/include/qt/QtCore/qpropertyanimation.h \
		../../../anaconda3/include/qt/QtCore/qvariantanimation.h \
		../../../anaconda3/include/qt/QtCore/qqueue.h \
		../../../anaconda3/include/qt/QtCore/qreadwritelock.h \
		../../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../../anaconda3/include/qt/QtCore/qresource.h \
		../../../anaconda3/include/qt/QtCore/qsavefile.h \
		../../../anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		../../../anaconda3/include/qt/QtCore/qsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		../../../anaconda3/include/qt/QtCore/qsettings.h \
		../../../anaconda3/include/qt/QtCore/qsharedmemory.h \
		../../../anaconda3/include/qt/QtCore/qsignalmapper.h \
		../../../anaconda3/include/qt/QtCore/qsignaltransition.h \
		../../../anaconda3/include/qt/QtCore/qsocketnotifier.h \
		../../../anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		../../../anaconda3/include/qt/QtCore/qstack.h \
		../../../anaconda3/include/qt/QtCore/qstandardpaths.h \
		../../../anaconda3/include/qt/QtCore/qstate.h \
		../../../anaconda3/include/qt/QtCore/qstatemachine.h \
		../../../anaconda3/include/qt/QtCore/qstorageinfo.h \
		../../../anaconda3/include/qt/QtCore/qstringlistmodel.h \
		../../../anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		../../../anaconda3/include/qt/QtCore/qtemporarydir.h \
		../../../anaconda3/include/qt/QtCore/QScopedPointer \
		../../../anaconda3/include/qt/QtCore/qtemporaryfile.h \
		../../../anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		../../../anaconda3/include/qt/QtCore/qtextcodec.h \
		../../../anaconda3/include/qt/QtCore/qthread.h \
		../../../anaconda3/include/qt/QtCore/qthreadpool.h \
		../../../anaconda3/include/qt/QtCore/qthreadstorage.h \
		../../../anaconda3/include/qt/QtCore/qtimeline.h \
		../../../anaconda3/include/qt/QtCore/qtimer.h \
		../../../anaconda3/include/qt/QtCore/qtimezone.h \
		../../../anaconda3/include/qt/QtCore/qtranslator.h \
		../../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../../anaconda3/include/qt/QtCore/quuid.h \
		../../../anaconda3/include/qt/QtCore/qwaitcondition.h \
		../../../anaconda3/include/qt/QtCore/qwineventnotifier.h \
		../../../anaconda3/include/qt/QtCore/qxmlstream.h \
		../../../anaconda3/include/qt/QtCore/qtcoreversion.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractnetworkcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkrequest.h \
		../../../anaconda3/include/qt/QtCore/QSharedDataPointer \
		../../../anaconda3/include/qt/QtCore/QString \
		../../../anaconda3/include/qt/QtCore/QUrl \
		../../../anaconda3/include/qt/QtCore/QVariant \
		../../../anaconda3/include/qt/QtNetwork/qauthenticator.h \
		../../../anaconda3/include/qt/QtNetwork/qdnslookup.h \
		../../../anaconda3/include/qt/QtNetwork/qhostinfo.h \
		../../../anaconda3/include/qt/QtNetwork/qhstspolicy.h \
		../../../anaconda3/include/qt/QtNetwork/qhttpmultipart.h \
		../../../anaconda3/include/qt/QtCore/QByteArray \
		../../../anaconda3/include/qt/QtCore/QIODevice \
		../../../anaconda3/include/qt/QtNetwork/QNetworkRequest \
		../../../anaconda3/include/qt/QtNetwork/qlocalserver.h \
		../../../anaconda3/include/qt/QtNetwork/qlocalsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkaccessmanager.h \
		../../../anaconda3/include/qt/QtCore/QVector \
		../../../anaconda3/include/qt/QtNetwork/QSslConfiguration \
		../../../anaconda3/include/qt/QtNetwork/qsslconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qsslsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtcpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslerror.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificate.h \
		../../../anaconda3/include/qt/QtNetwork/qssl.h \
		../../../anaconda3/include/qt/QtCore/QFlags \
		../../../anaconda3/include/qt/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../anaconda3/include/qt/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../anaconda3/include/qt/QtCore/QMetaType \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkconfiguration.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookie.h \
		../../../anaconda3/include/qt/QtCore/QList \
		../../../anaconda3/include/qt/QtNetwork/qnetworkcookiejar.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdatagram.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkdiskcache.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkinterface.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkproxy.h \
		../../../anaconda3/include/qt/QtNetwork/qnetworkreply.h \
		../../../anaconda3/include/qt/QtNetwork/QNetworkAccessManager \
		../../../anaconda3/include/qt/QtNetwork/qnetworksession.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qsctpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcertificateextension.h \
		../../../anaconda3/include/qt/QtNetwork/qsslcipher.h \
		../../../anaconda3/include/qt/QtNetwork/qssldiffiehellmanparameters.h \
		../../../anaconda3/include/qt/QtNetwork/qsslellipticcurve.h \
		../../../anaconda3/include/qt/QtCore/QHash \
		../../../anaconda3/include/qt/QtNetwork/qsslkey.h \
		../../../anaconda3/include/qt/QtNetwork/qudpsocket.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkversion.h \
		../../../anaconda3/include/qt/QtCore/QDataStream \
		../../../anaconda3/include/qt/QtCore/QTextStream \
		ui_mainwindow.h \
		net_speed.h \
		../../../anaconda3/include/qt/QtWidgets/QMessageBox \
		../../../anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../../../anaconda3/include/qt/QtWidgets/qdialog.h \
		../../../anaconda3/include/qt/QtWidgets/QFileDialog \
		../../../anaconda3/include/qt/QtWidgets/qfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

net_speed.o: net_speed.cpp packet.h \
		common.h \
		net_speed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o net_speed.o net_speed.cpp

common.o: common.cpp packet.h \
		net_speed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

tcpserver.o: tcpserver.cpp tcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/QTcpServer \
		../../../anaconda3/include/qt/QtNetwork/qtcpserver.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetworkglobal.h \
		../../../anaconda3/include/qt/QtCore/qglobal.h \
		../../../anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../../../anaconda3/include/qt/QtCore/qconfig.h \
		../../../anaconda3/include/qt/QtCore/qtcore-config.h \
		../../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../../anaconda3/include/qt/QtCore/qlogging.h \
		../../../anaconda3/include/qt/QtCore/qflags.h \
		../../../anaconda3/include/qt/QtCore/qatomic.h \
		../../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../../anaconda3/include/qt/QtCore/qmutex.h \
		../../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../../anaconda3/include/qt/QtNetwork/qtnetwork-config.h \
		../../../anaconda3/include/qt/QtCore/qobject.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../../anaconda3/include/qt/QtCore/qstring.h \
		../../../anaconda3/include/qt/QtCore/qchar.h \
		../../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../../anaconda3/include/qt/QtCore/qlist.h \
		../../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../../anaconda3/include/qt/QtCore/qiterator.h \
		../../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../../anaconda3/include/qt/QtCore/qpair.h \
		../../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../../anaconda3/include/qt/QtCore/qregexp.h \
		../../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../../anaconda3/include/qt/QtNetwork/qabstractsocket.h \
		../../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../../anaconda3/include/qt/QtCore/qdebug.h \
		../../../anaconda3/include/qt/QtCore/qhash.h \
		../../../anaconda3/include/qt/QtCore/qmap.h \
		../../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../../anaconda3/include/qt/QtCore/qlocale.h \
		../../../anaconda3/include/qt/QtCore/qvariant.h \
		../../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../../anaconda3/include/qt/QtCore/qvector.h \
		../../../anaconda3/include/qt/QtCore/qpoint.h \
		../../../anaconda3/include/qt/QtCore/qset.h \
		../../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../../anaconda3/include/qt/QtNetwork/qhostaddress.h \
		../../../anaconda3/include/qt/QtNetwork/QTcpSocket \
		../../../anaconda3/include/qt/QtNetwork/qtcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o tcpserver.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

